[tool.poetry]
name = "ci-cd"
version = "0.0.0"
description = ""
authors = ["Monteiro, Leandro (ESI) <leandro.monteiro@adp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
